### ISSUE TITLE
Sprint Drop Plan loads some javascript files from online "cdn"s

### ISSUE THREAD

**Issue by SMeisam** [yanivsegev/VSTS-DropPlan#1]
Hi
Our TFS server is not online. This extension loads some javascript files from online "cdn"s so could not be used on our server. The new version also does not work!
![snip_13960320100443](https://user-images.githubusercontent.com/29395384/27070195-2f766200-502d-11e7-9021-872eec10246b.png)
in this picture you can see what happen.

**Comment by yanivsegev** [comment]
Hi, This was fixed already, seems like you don't have the least version installed.  Please try to remove and download a new version - in the new version all files are stored locally on the server.

**Comment by SMeisam** [comment]
Hi
very thanks. yes I have the old version (1.0.22). in the new version that's OK.

**Comment by yanivsegev** [comment]
Great! Happy to see its working well for you.
Feel free to update your review on the visual studio marketplace.
