### ISSUE TITLE
Can't open tasks in Drop plan

### ISSUE THREAD

**Issue by CamfilPeter** [yanivsegev/VSTS-DropPlan#106]
When having tasks planned in the drop plan and try to open the task  from drop plan it just shows the update icon.
This happens only for 3 user at this point as far as we know.

is this a known bug or is this perhaps in conjunction with other extension? 
we have this issue for multiple versions and we have 2.0.2 installed

**Comment by sgtwilko** [comment]
@CamfilPeter can you provide a screen shot please?
Is this a new problem for those users?

There's been a long standing report about this issue (#84 ), I'd hoped upgrading the Azure Devops library would fix it.

I'm planning on looking at this issue shortly.

**Comment by sgtwilko** [comment]
Ok I think I've worked it out.
Sometimes it fails to load the task if we pass the `witId` as a `string`, converting to `int` seems to solve it.

**Comment by CamfilPeter** [comment]
Hi, I’m afraid it did not solve the issue.
You’re right it seems to be same issue as #84

**Comment by sgtwilko** [comment]
Hi @CamfilPeter the fix hasn't been merged yet, should be fixed in 2.0.3

**Comment by CamfilPeter** [comment]
According to the version installed we have V2.0.3

**Comment by CamfilPeter** [comment]
Great it’s working now, thanks
