### ISSUE TITLE
The capacity shown is double

### ISSUE THREAD

**Issue by joroSharp** [yanivsegev/VSTS-DropPlan#108]
The drop plan is showing double the capacity value in version 2.0.3.

That is, if, for example, the taskboard shows that a user has a capacity of 30 hours, the Drop plan shows 60 hours.
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/17873213/19186ddb-4ff0-4790-83a1-1a68ff9bd272)
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/17873213/e4d76505-2596-4fa0-8d15-962a44f61c96)

**Comment by sgtwilko** [comment]
@joroSharp will look at this later
