### ISSUE TITLE
Feature Request: Version that works with User Stories and Bugs

### ISSUE THREAD

**Issue by ravensorb** [yanivsegev/VSTS-DropPlan#11]
Love the ability to quickly assign tasks.  It would be fantastic to be able to do this at a User Story and Bug (or PBI) level to help with more program/project management at a higher level.

**Comment by yanivsegev** [comment]
Great idea,
I will try implement that in the future.

**Comment by jrhoadesRSI** [comment]
I love this, this is what my management wants to see but I need it to work with User Stories and Bugs
