### ISSUE TITLE
Bugs Drop Plan

### ISSUE THREAD

**Issue by pedrocbt21** [yanivsegev/VSTS-DropPlan#110]
Good afternoon,

I have two main bugs regarding the current drop plan.

The first is related to the fact that it is not possible to manually Rearrange Tasks for one of the teammates, and after we apply the filters of a letter and change the task again, it starts to give. And then it stops working again and so on... the line looks like this:
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/75639392/a29125d8-e4ad-4eeb-918b-ad41fc452cd7)

The other mistake is that the total number of hours doesn't look at the capacity of the team member in question.
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/75639392/d23dee9a-cc42-4fbc-bbca-6c64bb250e49)
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/75639392/568d56e4-5ab6-4d6e-aa63-5df2f3e8f105)

These errors have only started to occur since the pull request Bump minimist and mkdirp dependencies
#90. Is it not possible to put the stable 2023 version back online?

**Comment by sgtwilko** [comment]
Hi @pedrocbt21 

Can you confirm which version you are using, and what, if any errors you get in the console when you try to Rearrange tasks for that teammate.

**Comment by pedrocbt21** [comment]
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/75639392/940d9af2-5412-4769-baeb-51a026d8e925)
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/75639392/6037f85d-cb39-46d8-b8aa-0b42b2b643dd)

**Comment by pedrocbt21** [comment]
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/75639392/83a67036-cfde-49dd-a74b-1dbfca4971f0)

**Comment by pedrocbt21** [comment]
Pelo que vejo o erro não deve ser do drop plan... Deve ser erro da microsoft ao possuir dois user com emails exatamente iguais 
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/75639392/96e10513-419f-495b-9866-f4c657bca1a6)

**Comment by yanivsegev** [comment]
Hi,
Please check version 2.0.11 - Is it still going? if so, can you please share the new error messages?

**Comment by pedrocbt21** [comment]
Good morning,

The error has been fixed and it's working again :) 

Thanks for your help.
