### ISSUE TITLE
Wrong Hours Capacity

### ISSUE THREAD

**Issue by pedrocbt21** [yanivsegev/VSTS-DropPlan#111]
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/75639392/40071738-e618-4fad-91ae-a7d1deb8c672)
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/75639392/7f060f39-ae2c-4a8d-b44f-490545c6ffd5)

I have one user without capacity and in the drop plan he appers with capacity.

**Comment by sgtwilko** [comment]
Yeah I spotted that we seem to apply 6 hours a day if someone has been added to the capacity but doesn't have time allocated.

@yanivsegev  I'm going to set this to zero in my next PR as I think this doesn't make sense, and I also think that previously this line was probably not being hit.
