### ISSUE TITLE
Error putting a task on Mondays

### ISSUE THREAD

**Issue by mjavier87** [yanivsegev/VSTS-DropPlan#118]
Good mornign. 
Since the last update, the tasks that were on Monday were moved to Tuesday. It's not possible to arranged them again to Monday.
This happens for all sprints. 
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/159581219/aed0ccbb-0da4-44ff-94e9-c960cdb4e32a)

**Comment by yanivsegev** [comment]
Sorry to hear that, 2.1.7 was focusing on improving logs.
Do you see any console errors on developer tools? can you send the console log print - mainly on the load process? 
Does it happen on all Mondays or just the first Monday of a sprint?

**Comment by sgtwilko** [comment]
Hi @lucasllano 

Is it any Monday in the sprint, or just the first day of the sprint?

Do you have any days configured for the team as non-working days?

**Comment by lucasllano** [comment]
It is any Monday. We mark Saturday and Sunday as non-working days but I've just tried selecting all days as work-days and drop plan is still showing Monday disabled.

![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/4128419/51225b01-6fef-4f06-94a3-7e093d82b4b0)

![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/4128419/bde4cc60-8d5f-4d52-b87f-bda5f8a0b152)

**Comment by lucasllano** [comment]
I changed sprint dates from Sunday 18 to Friday 25. Monday doesn't show disabled (Sunday yes which shouldn't) but still when you drop a task on Monday it will be automatically moved to Tuesday.

![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/4128419/1338d840-5cd0-4978-bdac-027475cc5a8d)

**Comment by lucasllano** [comment]
OK, update. Using spring dates Sunday to Sunday and marking all working-days doesn't show disabled days and enables you to drop tasks on Mondays. Maybe it's something with time-zones. When you move a task the Start Date value is placed at 9 PM (we use UTC-3)

![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/4128419/5a00def4-8944-4f1a-a676-b83b302afba7)
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/4128419/54dbe927-7731-4f38-9d0a-62e0f5efa914)

**Comment by sgtwilko** [comment]
Hi @lucasllano 

Think you could be right.

I bet the DevOps is sending utc days in one place and using local time in another.

**Comment by sgtwilko** [comment]
@yanivsegev I think this may be related to a change I made to support the hiding of the non-working days.
I'm happy to look at this over the weekend.

**Comment by sgtwilko** [comment]
ok, I've managed to simulate the issue.

**Comment by sgtwilko** [comment]
everything showing as scheduled one day off because the dates are stored in DevOps in UTC, but rendered using the browsers timezone.
so 2024-02-12T00:00Z is 2024-02-13T03:00 (-3)

**Comment by sgtwilko** [comment]
@lucasllano @yanivsegev @mjavier87 PR is in with this fixed.
Once you have 2.1.8 let us know if there's still an issue.

**Comment by lucasllano** [comment]
thank you @sgtwilko for adressing this issue! @yanivsegev I don´t see version 2.1.8 published on visual studio marketplace. Once you publish a new version a revision process takes place or samething else that delays the publication?  https://marketplace.visualstudio.com/items?itemName=yanivsegev.Drop-plan-extension&targetId=c387cde5-7798-430f-af0a-9da08e94385a&utm_source=vstsproduct&utm_medium=ExtHubManageList

**Comment by mjavier87** [comment]
thanks @sgtwilko and @yanivsegev for your support.
