### ISSUE TITLE
Cannot read properties of undefined (reading 'length;)

### ISSUE THREAD

**Issue by Alfadbhq** [yanivsegev/VSTS-DropPlan#122]
Error occurred when opening Drop plan.

 
![cannot read properties error](https://github.com/yanivsegev/VSTS-DropPlan/assets/156981307/009d49e0-0494-4a62-8bca-15bab342fb1e)

**Comment by yanivsegev** [comment]
Hi @Alfadbhq,
I see on the logs this failure which relates to a task that spans beyond the sprint working days.
I added more logs to try to better understand the root cause.
Will keep you updated :-).

**Comment by Alfadbhq** [comment]
Hi @sgtwilko,
It's working now as expected.  Thanks for the immediate resolution.
