### ISSUE TITLE
Drop plan is not visible in TFS 2015

### ISSUE THREAD

**Issue by allenjp4432** [yanivsegev/VSTS-DropPlan#13]
I have recently added the Drop Plan to a TFS2015 instance and the extension is not visible.

**Comment by allenjp4432** [comment]
Just an update we are using the scrum process templates and we are using TFS 2015 update 3

**Comment by yanivsegev** [comment]
I uploaded a new version, please try again.
If it's still not working, can you please attach the Chrome console log?

Yaniv.
