### ISSUE TITLE
Sprint starting 1 day early and ending 1 day early

### ISSUE THREAD

**Issue by skyrimax** [yanivsegev/VSTS-DropPlan#132]
When we opened Drop Plan this morning for our palning, we noticed that there is a column for sunday march 10th
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/46486903/71266957-c6ed-44ce-9c21-e3db9d5e50ba)
 And the column for friday march 15th is missing.
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/46486903/49f57e22-371e-4a91-9a6c-c60101df0c65)
Our sprint is set to start on monday march 11th and finish friday march 15th
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/46486903/9c8e2e0c-330a-4203-8b0f-6df1355e7751)
We are on version 2.2.4 and our time zone is Eastern Daylight Time. We moved time forward this past weekend (from saterday march 9th to sunday march 10th)

Edit: A collegue just informed me the issue appeared last friday, when our Drop Plan extension was updated to 2.2.4

**Comment by yanivsegev** [comment]
Hi @skyrimax ,
We recently changed our time management to fix some other issues - this might be the cause of this bug.
You can disable it in the Project Settings -> Drop Plan Settings -> "Use new time management".

Can you please check this with the new settings and see if it gets better?

**Comment by skyrimax** [comment]
Thanks you, it worked! I will close this issue.Thanks for your help.
