### ISSUE TITLE
Drop Plan tasks land one day backward of where I release my mouse

### ISSUE THREAD

**Issue by GQ16** [yanivsegev/VSTS-DropPlan#133]
To recreate: Create a sprint and add pbi’s and tasks. Open the drop plan under the “Sprints” view. Drag a task to a given day. When you release your mouse, you’ll notice the Task doesn’t land under the day where your mouse was released, it instead drops them on the day before.

Theory: I believe this is due to the improper sprint dates being shown in the drop plan, for example I have a sprint that runs from March 13th - 26th but the dates in the drop plan show March 12th - 25th. Hence when I drop the task in the zone which should represent a certain day, it instead shows up shifted back one day because the whole drop plan is shifted back one day.

Images:
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/107271596/890e7e23-d2ae-4f15-93c9-bd03dc7e6036)

**Comment by yanivsegev** [comment]
Hi @GQ16,

There is some inconsistency in DevOps timezones that we didn't fully figure it up - sorry about that - for some users we need to correct the time zone (but for the rest we shouldn't).
If you go to the drop plan settings page (under the project settings area) - there is a "new time management" option - can you try to toggle it and see if it helps?

Can you please send me the below to help me identify the issue:
* Your browser's settings for the time and date formats
* Your organization or server's time and date formats
* Your personal profile Time and Locale setting.

**Comment by GQ16** [comment]
That fixed it, thank you @yanivsegev !
