### ISSUE TITLE
Syncing Drop plan with an entry field like Scheduled Start Date / Start Date

### ISSUE THREAD

**Issue by tpramiti** [yanivsegev/VSTS-DropPlan#134]
It would be great if there was a two way relation between the drop plan and any of the date entry field in azure. So that

1. Dragging an item changed the start and end date of the task/user story/ bug
2. Changing the Start Date/ Scheduled Start date reflects on the drop plan.

**Comment by yanivsegev** [comment]
Hi @tpramiti,
The drop plan uses the standard fields below to store its data.
Are you using any other fields?

Fields list:
Microsoft.VSTS.Scheduling.StartDate
Microsoft.VSTS.Scheduling.FinishDate

Microsoft.VSTS.Scheduling.OriginalEstimate
Microsoft.VSTS.Scheduling.CompletedWork
Microsoft.VSTS.Scheduling.RemainingWork
