### ISSUE TITLE
Unknown error occured

### ISSUE THREAD

**Issue by Alfadbhq** [yanivsegev/VSTS-DropPlan#135]
When running Drop Plan, error popup "... bedded page at yanivsegev.galleryycdn.vsassets.io.says
TF10216: Azure DevOps services are currently unavailable
![UnknownError1](https://github.com/yanivsegev/VSTS-DropPlan/assets/156981307/322bb36f-7766-4929-b35c-a78c1369d97e)
![UnknownError2](https://github.com/yanivsegev/VSTS-DropPlan/assets/156981307/ecc18260-5f53-407a-a4b7-5d0379c613aa)

**Comment by yanivsegev** [comment]
Does it happen often?
Can you please attach the console log and the HAR file? (F12 -> Network -> Export HAR)
