### ISSUE TITLE
Drop plan doesn't work

### ISSUE THREAD

**Issue by coulpi** [yanivsegev/VSTS-DropPlan#138]
Hello everyone,

On the "Sprints" screen and under the "Drop Plan" tab, I receive the message: "Sprint Drop Plan by Yaniv Segev failed to load. Learn more about this extension, including available support options." In the Drop Plan extension settings screen, I also receive the message: "Sprint Drop Plan is taking longer than expected to load," and the page remains stuck loading.

Does anyone have any ideas?

Thank you!

![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/7715696/98e3813a-684d-4997-854c-34e2bbf778a0)

![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/7715696/07540947-1b10-4ea3-9e01-af2be02c90e4)

**Comment by sgtwilko** [comment]
@coulpi is this still happening?
