### ISSUE TITLE
Project Time Zone not respected in dates resulting in tasks automatically starting on Sunday

### ISSUE THREAD

**Issue by Fabio-Zigliani** [yanivsegev/VSTS-DropPlan#14]
Hello 
our project timezone is New Zealand but the dates are in US format and as you can see in the image it is automatically scheduling start dates on a Sunday.

It appears to be a timezone issue...

Thanks,

Fabio 

![image](https://user-images.githubusercontent.com/5210887/29198889-fe1d0bf8-7e9b-11e7-9c23-7a572dd0be63.png)

**Comment by yanivsegev** [comment]
Hi,

I updated the display to show based on local date.
Please see if it works for you.
