### ISSUE TITLE
Feature Request - Ability to Remove day-off on team-wide days off

### ISSUE THREAD

**Issue by Lockszmith-GH** [yanivsegev/VSTS-DropPlan#140]
This is for multi-time-zone teams or for teams working in shifts, where a weekend and holiday might affect most of the team, but not all.

Thus, for example if Sunday is a holiday for most of the members, but not for some, allow them to right-click --> Remove day-off.

**Comment by yanivsegev** [comment]
Hi @Lockszmith-GH,
Please see the comment in the "capacity" tab for "team days off" - "These days off apply to the whole team".
Maybe try to set the "team days off" only on those days and mark the rest as personal days off.

**Comment by Lockszmith-GH** [comment]
Yes, that obviously works. 

But I'm the odd man out, the rest of the team rely on this for planning.

The request will introduce a quality-of-life improvement.

It also makes sense when doing shifts - like working weekends (it might be rare in software shops, but it does exist at statups where somebody is working to be able to cover production issues during the weekends/holidays)

Thanks for looking into this. You are definitely not obligated to follow through if this doesn't make sense to you.

**Comment by yanivsegev** [comment]
Sorry, you will need to ask Microsoft to support this in Azure first.
