### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by mguerrer** [yanivsegev/VSTS-DropPlan#15]
Steps to reproduce:
1- Download yanivsegev.Drop-plan-extension-1.0.46.vsix
2- Execute
![image](https://user-images.githubusercontent.com/1924065/29434856-08e46584-837b-11e7-94b3-4601e7c46bb6.png)

The log file is:
17-08-2017 18:35:23 - Microsoft VSIX Installer
17-08-2017 18:35:23 - -------------------------------------------
17-08-2017 18:35:23 - vsixinstaller.exe version:
17-08-2017 18:35:23 - 15.0.26430.4 built by: D15SVC
17-08-2017 18:35:23 - -------------------------------------------
17-08-2017 18:35:23 - Command line parameters:
17-08-2017 18:35:23 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VSIXInstaller.exe,C:\Users\mguerrero\Downloads\yanivsegev.Drop-plan-extension-1.0.46.vsix
17-08-2017 18:35:23 - -------------------------------------------
17-08-2017 18:35:23 - Microsoft VSIX Installer
17-08-2017 18:35:23 - -------------------------------------------
17-08-2017 18:35:23 - Initializing Install...
17-08-2017 18:35:23 - Detalles de la extensión...
17-08-2017 18:35:23 - 	Identifier         : Drop-plan-extension
17-08-2017 18:35:23 - 	Name               : Sprint Drop Plan
17-08-2017 18:35:23 - 	Author             : yanivsegev
17-08-2017 18:35:23 - 	Version            : 1.0.46
17-08-2017 18:35:23 - 	Description        : Plan and track your sprint with a calendar based view.
17-08-2017 18:35:23 - 	Locale             : en-US
17-08-2017 18:35:23 - 	MoreInfoURL        : 
17-08-2017 18:35:23 - 	InstalledByMSI     : False
17-08-2017 18:35:23 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
17-08-2017 18:35:23 - 
17-08-2017 18:35:23 - 	SignatureState     : Unsigned
17-08-2017 18:35:23 - 	Productos admitidos : 
17-08-2017 18:35:23 - 		Microsoft.VisualStudio.Services
17-08-2017 18:35:23 - 			Version : 
17-08-2017 18:35:23 - 
17-08-2017 18:35:23 - 	Referencias        : 
17-08-2017 18:35:23 - Detalles de la firma...
17-08-2017 18:35:23 - 	Extension is not signed.
17-08-2017 18:35:23 - 
17-08-2017 18:35:23 - Buscando productos aplicables...
17-08-2017 18:35:23 - Producto instalado encontrado: Microsoft Visual Studio Enterprise 2015
17-08-2017 18:35:23 - Producto instalado encontrado: Microsoft Visual Studio Professional 2015
17-08-2017 18:35:23 - Producto instalado encontrado: Microsoft Visual Studio Community 2015
17-08-2017 18:35:23 - Producto instalado encontrado: Microsoft Visual Studio 2015 Shell (Integrated)
17-08-2017 18:35:23 - Producto instalado encontrado: Ubicación global
17-08-2017 18:35:23 - Producto instalado encontrado: Visual Studio Enterprise 2017
17-08-2017 18:35:23 - VSIXInstaller.NoApplicableSKUsException: Esta extensión no se puede instalar en ninguno de los productos instalados actualmente.
   en VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   en VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   en VSIXInstaller.App.Initialize()
   en System.Threading.Tasks.Task`1.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()

**Comment by yanivsegev** [comment]
I uploaded a new version, please try again.

**Comment by mguerrer** [comment]
Same error.     This is the log.

21-08-2017 17:45:42 - Microsoft VSIX Installer
21-08-2017 17:45:42 - -------------------------------------------
21-08-2017 17:45:42 - Initializing Install...
21-08-2017 17:45:43 - Detalles de la extensión...
21-08-2017 17:45:43 - 	Identifier         : Drop-plan-extension
21-08-2017 17:45:43 - 	Name               : Sprint Drop Plan
21-08-2017 17:45:43 - 	Author             : yanivsegev
21-08-2017 17:45:43 - 	Version            : 1.0.51
21-08-2017 17:45:43 - 	Description        : Plan and track your sprint with a calendar based view.
21-08-2017 17:45:43 - 	Locale             : en-US
21-08-2017 17:45:43 - 	MoreInfoURL        : 
21-08-2017 17:45:43 - 	InstalledByMSI     : False
21-08-2017 17:45:43 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
21-08-2017 17:45:43 - 
21-08-2017 17:45:43 - 	SignatureState     : Unsigned
21-08-2017 17:45:43 - 	Productos admitidos : 
21-08-2017 17:45:43 - 		Microsoft.VisualStudio.Services
21-08-2017 17:45:43 - 			Version : 
21-08-2017 17:45:43 - 
21-08-2017 17:45:43 - 	Referencias        : 
21-08-2017 17:45:43 - Detalles de la firma...
21-08-2017 17:45:43 - 	Extension is not signed.
21-08-2017 17:45:43 - 
21-08-2017 17:45:43 - Buscando productos aplicables...
21-08-2017 17:45:43 - Producto instalado encontrado: Microsoft Visual Studio Enterprise 2015
21-08-2017 17:45:43 - Producto instalado encontrado: Microsoft Visual Studio Professional 2015
21-08-2017 17:45:43 - Producto instalado encontrado: Microsoft Visual Studio Community 2015
21-08-2017 17:45:43 - Producto instalado encontrado: Microsoft Visual Studio 2015 Shell (Integrated)
21-08-2017 17:45:43 - Producto instalado encontrado: Ubicación global
21-08-2017 17:45:43 - VSIXInstaller.NoApplicableSKUsException: Esta extensión no se puede instalar en ninguno de los productos instalados actualmente.
   en VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   en VSIXInstaller.App.InitializeInstall()
   en System.Threading.Tasks.Task.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()

**Comment by yanivsegev** [comment]
Hi,
On the log i see "Microsoft Visual Studio Enterprise 2015" and such, Are you trying to install that on the TFS server or on your local VS 2015? this is intended for the TFS server.
