### ISSUE TITLE
installed, but no users/tasks visible

### ISSUE THREAD

**Issue by odanr** [yanivsegev/VSTS-DropPlan#17]
same issue in English.
Burndown Failed to load resource: the server responded with a status of 400 (TF401315: Invalid chart options.  Chart options may not be null, and the width and height must be greater than zero and less than 10000.)
DropPlanVSS.js:13 Stating. (0.125 ms.)
DropPlanVSS.js:25 VSS init. (2.1200000000000045 ms.)
cdn.trackjs.com/releases/current/tracker.js:15 VSS loaded. (311.96500000000003 ms.)
cdn.trackjs.com/releases/current/tracker.js:15 Team data loaded. (794.7600000000002 ms.)
cdn.trackjs.com/releases/current/tracker.js:15 Iteration data loaded. (994.865 ms.)
cdn.trackjs.com/releases/current/tracker.js:15 Work items data loaded. (1393.9150000000002 ms.)
cdn.trackjs.com/releases/current/tracker.js:15 Setup items (1394.3850000000002 ms.)
cdn.trackjs.com/releases/current/tracker.js:15 Rendering. (1441.8600000000001 ms.)
cdn.trackjs.com/releases/current/tracker.js:15 Attach events
cdn.trackjs.com/releases/current/tracker.js:15 Drawing Relations (2204.66 ms.)
cdn.trackjs.com/releases/current/tracker.js:15 Drawing Relations (2556.3450000000003 ms.)
2yanivsegev.gallerycdn.vsassets.io/extensions/yanivsegev/drop-plan-extension/1.0.51/1503294890768/null Failed to load resource: the server responded with a status of 404 ()

**Comment by odanr** [comment]
![image](https://user-images.githubusercontent.com/31204487/29510098-4f8e58ec-8663-11e7-8578-6483c38b6cc1.png)

**Comment by yanivsegev** [comment]
Hi,
I uploaded a new version with some fixes, please give it a try and let me know if it worked.

**Comment by odanr** [comment]
still the same, uninstalled and reinstalled - the same

**Comment by yanivsegev** [comment]
Hi,
Can you please make sure that you have work items in the current iteration of type 'Task'?
Are you using the default schema or a modified one? can you check that the below columns exists in your schema:

System.WorkItemType = 'Task'
System.State
System.AssignedTo
Microsoft.VSTS.Scheduling.StartDate
Microsoft.VSTS.Scheduling.FinishDate
Microsoft.VSTS.Common.BacklogPriority
Microsoft.VSTS.CMMI.Blocked
System.Title
System.Description
Microsoft.VSTS.Scheduling.RemainingWork

**Comment by odanr** [comment]
how can i check this on vsts ? 
![image](https://user-images.githubusercontent.com/31204487/30013465-72329b00-914f-11e7-82a7-5ef5ef601330.png)

**Comment by yanivsegev** [comment]
Simply by running a query with WorkItemType = 'Task' and Iteration Path = @CurrentIteration and Area path = all your paths..
The drop plan will show those items, If you don't get any results then the drop plan will be emply.
