### ISSUE TITLE
User Stories instead of tasks

### ISSUE THREAD

**Issue by PerryRobertson** [yanivsegev/VSTS-DropPlan#18]
Hi, I love the idea of this project.  However we aren't using tasks in our project.  We only have user stories.  Is it possible to plan stories instead of tasks?

**Comment by yanivsegev** [comment]
Hi, I plan to extend the view into PBIs/UserStories in the future.
Interesting way of work, The TFS is designed to work on tasks as a working item, i recommend you to use it.
