### ISSUE TITLE
Not visible under TFS 2015.4

### ISSUE THREAD

**Issue by hdesouky** [yanivsegev/VSTS-DropPlan#19]
I installed the extension on premises however there is not link appeared beside the sprint capacity link
there is nothing in the Chrome console log to share!

**Comment by yanivsegev** [comment]
I uploaded a few fixes, is it still not working?

**Comment by ktprasanth** [comment]
I have installed it recently on the same TFS 2015 still unable to see.

**Comment by yanivsegev** [comment]
Can you please send a screenshot? chrome console log?
