### ISSUE TITLE
After Installing the Add-In on our TFS (2015 Update 3) server i cant see the "Drop Plan" Tab under the relevant sprint.

### ISSUE THREAD

**Issue by RonnyKay** [yanivsegev/VSTS-DropPlan#2]
Using Chrome Browser "Version 59.0.3071.86 (Official Build) (64-bit)"

![image](https://user-images.githubusercontent.com/10451540/27185069-db075910-51ec-11e7-9b87-afd022fe4060.png)

Here is a Console Log:

![image](https://user-images.githubusercontent.com/10451540/27185881-577002fc-51ef-11e7-87a4-34701a8a6e9f.png)

**Comment by yanivsegev** [comment]
Those screenshots relates to other extension that you are running, TaskBoardEnhancer. Can you send the relevat screenshots?

**Comment by RonnyKay** [comment]
Hi Yaniv,

I have disabled the TaskBoardEnhancer Extension and it seems that their is no Error messages regarding the  "Drop Down" 

but here is the Console Snapshot that i am getting now:

![image](https://user-images.githubusercontent.com/10451540/27385336-eeff168a-569a-11e7-85ac-939d5d418937.png)
