### ISSUE TITLE
Capacity on drop plan doesn't match capacity in time box

### ISSUE THREAD

**Issue by SamanthaEntwistle** [yanivsegev/VSTS-DropPlan#21]
Hi,

We've noticed the available capacity isn't correct on the drop plan version of the person's capacity.
In Drop plan
![image](https://user-images.githubusercontent.com/27805840/31822998-8a986e46-b5a2-11e7-9f8a-f2b86ddbd7d6.png)

Its showing me as 30h available by for this time box I'm only available 14h
![image](https://user-images.githubusercontent.com/27805840/31823034-a0c87968-b5a2-11e7-9849-109c671f27c6.png)
![image](https://user-images.githubusercontent.com/27805840/31823037-a4005e3e-b5a2-11e7-9a3d-192ca56ac34e.png)

Everybody seems to be calculated on 6hr day? We have custom setting.

Thanks
Sam

**Comment by yanivsegev** [comment]
Issue fixed.
Can you please try again and see if it works as expected?

**Comment by SamanthaEntwistle** [comment]
Hi,

Yes that’s now fixed ☺

Is there any way to change the dates to UK format? I’ve changed my preferences in my profile but it doesn’t seem to apply to drop plan?

Thanks
Sam

Samantha Entwistle
Testing Strategy Manager

[cid:image003.jpg@01D35485.EF11C8A0]

Premex Group
Tel - 01204 478 419
Mobile – 07500 781178
Fax- 0333 600 1680
Email –samantha,entwistle@premex.com<mailto:adam.priest@premex.com>
Website- www.premexgroup.com<http://www.premexgroup.com/>

Calls may be recorded for training and quality purposes

**Comment by yanivsegev** [comment]
Hi,
I updated the dates, Can please verify it is working for you?

**Comment by SamanthaEntwistle** [comment]
Hi,

No I don’t think it is.
[cid:image001.png@01D361DF.DD512400]

This is how my preferences are set

[cid:image002.png@01D361DF.DD512400]

Thanks

Sam

Samantha Entwistle
Testing Strategy Manager

[cid:image005.jpg@01D361DF.E3274800]

Premex Group
Tel - 01204 478 419
Mobile – 07500 781178
Fax- 0333 600 1680
Email –samantha,entwistle@premex.com<mailto:adam.priest@premex.com>
Website- www.premexgroup.com<http://www.premexgroup.com/>

Calls may be recorded for training and quality purposes

**Comment by yanivsegev** [comment]
Fixed it again, please try again.

**Comment by SamanthaEntwistle** [comment]
Looking good!

Thanks

Sam

Samantha Entwistle
Testing Strategy Manager

[cid:image003.jpg@01D3675E.B2142DD0]

Premex Group
Tel - 01204 478 419
Mobile – 07500 781178
Fax- 0333 600 1680
Email –samantha,entwistle@premex.com<mailto:adam.priest@premex.com>
Website- www.premexgroup.com<http://www.premexgroup.com/>

Calls may be recorded for training and quality purposes
