### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by davidasconsulting** [yanivsegev/VSTS-DropPlan#22]
Hi, 

I am running TFS Update 3 and I get this error when installing this extension:

Extension manifest file format is invalid. 

Can you help?

David

**Comment by davidasconsulting** [comment]
I solved that... it needed to be installed from
/tfs/_gallery/manage

but I now installed it, but I can't find it anywhere on my TFS... How can I locate it?

**Comment by davidasconsulting** [comment]
As per your request on my review, I am posting details of my issue here.  The extension is installed.  See the picture here:
![image](https://user-images.githubusercontent.com/7915911/32741258-44f9ef1c-c8ae-11e7-95d1-93cd6c49fa2d.png)
We have only one Team Collection, so I know it is installed in the right one. Yet, when I go to the Iteration, I don't see the tab for DropPlan (see this picture)

![image](https://user-images.githubusercontent.com/7915911/32741425-ddb8c372-c8ae-11e7-9331-71d43851cefb.png)

Please let me know what else I can provide to help you diagnose

**Comment by yanivsegev** [comment]
From the screenshot it looks like it was only downloaded to your local store and not installed on your TFS, are you sure that you installed it?

**Comment by davidasconsulting** [comment]
Definitely installed

![image](https://user-images.githubusercontent.com/7915911/32744650-e8daad1a-c8b8-11e7-9559-093826467474.png)

**Comment by davidasconsulting** [comment]
Hi Yaniv,

Any ideas here?  Want to use this for my iteration planning this week.  

Thanks

David

**Comment by yanivsegev** [comment]
Sorry, I don't have any idea, it seems not related to the extension itself but to installations issues that you have.
Maybe try to uninstall and reinstall again?
Are you able to install and use other extensions?

**Comment by davidasconsulting** [comment]
Hi Yaniv,

We are able to install other extensions and they work.  I tried uninstalling and reinstalling as well.

I am certain that it is an issue in our environment.  Is there anything you could do to help debug this?  Happy to arrange access if that would help

David

**Comment by yanivsegev** [comment]
Hi
Sorry, I'm not a TFS DevOps expert but i can recommend you to update your system to the latest release, its an easy update and you will get lots of new features and maybe it will fix the above issue as well.
Hope you will solve it soon and try my extension. Can you please update your review at the tfs marketplace accordingly?
