### ISSUE TITLE
"Browser is Not Supported"

### ISSUE THREAD

**Issue by amirharel** [yanivsegev/VSTS-DropPlan#24]
Hi,

I've installed the extension on tfs 2017 on-premise.
I'm getting:  "Browser is Not Supported"

I am getting a Reference Error for: "trackjs" at the file: "DropPlanVSS.js" at line 56

pls help

Cheers
Amir Harel 👍

**Comment by yanivsegev** [comment]
Do you have internet access from your client? 
I uploaded a new version that should ignore that file if you don't have internet access, can you please try again and let me know?

**Comment by amirharel** [comment]
Hi,

Still doesn't work.
Failed at: tracker.js & analytics.js
m=s.getelementsByTagName.....
row 23
got: "Failed to load: net::ERR_NAME_NOT_RESOLVED" (index.html)

Cheers
Amir Harel

**Comment by yanivsegev** [comment]
I uploaded another fix - hope now it's really being fixed, can you verify that it works for you?
