### ISSUE TITLE
Incorrect day being displayed if the timezone is set to UTC+8:00

### ISSUE THREAD

**Issue by Jerich0** [yanivsegev/VSTS-DropPlan#25]
We just recently installed this and noticed that for users that have their timezone set to UTC+8:00, the days associated to the dates are incorrect. See screenshot below:

![image](https://user-images.githubusercontent.com/6543299/33486317-8c45bdee-d6e4-11e7-9285-d0909f16958b.png)

December 1st, 2017 is a Friday however, it's being displayed as a Saturday. This is fine for users that have a US timezone set.

**Comment by yanivsegev** [comment]
I uploaded a fix, can you verify that it works for you?

**Comment by Jerich0** [comment]
Yes, this is now fixed. Thanks!
