### ISSUE TITLE
Incorrect Days displaying against Date.

### ISSUE THREAD

**Issue by pramodb05** [yanivsegev/VSTS-DropPlan#26]
I'm facing issue with dates display, The Days assigned to the dates are incorrect or we can say a Day behind.
Today is Friday 15th Dec. and it is displaying 14th Dec. as Friday.
![error](https://user-images.githubusercontent.com/7371561/34029878-af21af4c-e190-11e7-9bff-f7495f15bfca.JPG)

**Comment by yanivsegev** [comment]
I uploaded a fix, can you verify that it works for you?

**Comment by pramodb05** [comment]
Hi Yaniv,
It's working fine for me, I hope it'll work good for all. You did a great job.
Thanks.
