### ISSUE TITLE
Call to server failed

### ISSUE THREAD

**Issue by PhilTheDude** [yanivsegev/VSTS-DropPlan#3]

**Comment by ryanisjones** [comment]
I am getting the same error message after installing. Has this issue been solved?

**Comment by SamanthaEntwistle** [comment]
Are you using IE?

**Comment by ryanisjones** [comment]
Nope,

I'm using chrome.

**Comment by ryanisjones** [comment]
[image: Inline images 2]
When I refresh I get the same issue.
[image: Inline images 3]

Thanks

**Comment by ryanisjones** [comment]
![image](https://user-images.githubusercontent.com/29981498/28420626-9fdcd4d0-6d5a-11e7-9b3e-a05e70c0da55.png)
![image](https://user-images.githubusercontent.com/29981498/28420654-b57748c0-6d5a-11e7-988f-fb90c09eb8e1.png)
![image](https://user-images.githubusercontent.com/29981498/28420678-cd30c5ae-6d5a-11e7-97d7-8218ff863253.png)

Hi Phil, any word yet on why this may be happening? 
Thanks
