### ISSUE TITLE
Future time boxes start on Sunday and Friday/Sat showing as weekend

### ISSUE THREAD

**Issue by SamanthaEntwistle** [yanivsegev/VSTS-DropPlan#30]
Hi,

![image](https://user-images.githubusercontent.com/27805840/37713391-b639ac8e-2d0e-11e8-9375-9502665ee405.png)

The future time boxes are showing as starting on Sunday on the drop plan suddenly?

The Timebox starts on the 26/3 but its showing in dropplan as the 25/3 and Friday/Saturday are showing as holiday.

All future timeboxes are like this - but the current one is right?

Has something changed?

Thanks
Sam

**Comment by yanivsegev** [comment]
Is this still going? I fixed a few issues there.
