### ISSUE TITLE
Can't open DropPlan

### ISSUE THREAD

**Issue by EfiGabay** [yanivsegev/VSTS-DropPlan#32]
Hi, I'm getting this message it happens only in my user

Sprint Drop Plan by Yaniv Segev failed to load.Learn More about this extension, including available support options.

**Comment by rsheynin** [comment]
I have same issues

**Comment by EfiGabay** [comment]
I have already figured out that Internet Explorer doesn't support the DropPlan.
I use Chrome and it's fine.
Though you do have a problem in the DropPlan since yesterday, the names were not displayed.

[cid:image001.png@01D3F1B8.228340E0]

Best regards,

Effi Gabay
HP Indigo – IT Section
Development and Support Team
Einstein 18 Floor 4 Room 410 Park Hamada Nes Ziyona
Fax: +972-8-9388042
Lync Phone: +972-77-2212162
Cell Phone: +972-54-4902362

**Comment by yanivsegev** [comment]
Issue fixed, thanks to @MarkGaze 
Can you please confirm it is working now?
