### ISSUE TITLE
Task Assignee showing as [object Object]

### ISSUE THREAD

**Issue by gerrylowe** [yanivsegev/VSTS-DropPlan#33]
Sometime in the last few days, Drop Plan has stopped identifying the assignee of a Task, resulting in the display shown in the attachment.  This illustration is for a fresh VSTS project (agile template, no customization, 1 story + 1 task). 
![drop plan](https://user-images.githubusercontent.com/10186807/40165606-5430be42-59b4-11e8-8260-f3f875ef96d8.png)

**Comment by kousei2040** [comment]
I am having the same issue with our VSTS plugin. We cannot use it anymore at the name does is not showing properly anymore. Tested using Microsoft EDGE and Chrome but with the same result.

**Comment by rsheynin** [comment]
I am having the same issue with this as a VSTS plugin. 
![dropplanusersbugscapture](https://user-images.githubusercontent.com/4847580/40347976-cbe714e6-5daa-11e8-9604-1a606a724929.PNG)

**Comment by yanivsegev** [comment]
Pull request merged and published.
Please check now.
