### ISSUE TITLE
Not openingn up

### ISSUE THREAD

**Issue by nfernandoens** [yanivsegev/VSTS-DropPlan#35]
My team loved the tool however since 20/05/2018 it has stopped loading 
![tsodropplanissue](https://user-images.githubusercontent.com/39471510/40285591-8d87847e-5c8d-11e8-8106-f0aed1034aa4.png)

**Comment by EdwinJunior** [comment]
Same problem.

**Comment by mpatel29** [comment]
Same issue, is anyone looking into this?

**Comment by yanivsegev** [comment]
Issue fixed, thanks to @MarkGaze 
Can you please confirm it is working now?
