### ISSUE TITLE
Bug - Team Members not Recognized 

### ISSUE THREAD

**Issue by rsheynin** [yanivsegev/VSTS-DropPlan#36]
Drop Plan does not recognize team members and put all the Task in one Bulk as [object Object ]

**Comment by rsheynin** [comment]
![dropplanusersbugscapture](https://user-images.githubusercontent.com/4847580/40347912-9bfd7798-5daa-11e8-974b-dd4aff7cf0ce.PNG)

**Comment by MaxVL** [comment]
Experiencing the same issue. Team members are not visible. 
![image](https://user-images.githubusercontent.com/3618266/40428826-29f2e7a8-5e6f-11e8-8776-d42eddaff6aa.png)

**Comment by yanivsegev** [comment]
Issue fixed, thanks to @MarkGaze 
Can you please confirm it is working now?
