### ISSUE TITLE
Drop plan stuck on loading

### ISSUE THREAD

**Issue by dacdelston** [yanivsegev/VSTS-DropPlan#37]
We have had issues with many of projects not loading the drop plan and being stuck on the loading screen.  

Any ideas as to how to solve this?

![brokendropplan](https://user-images.githubusercontent.com/6620944/40366117-5c25b29e-5da4-11e8-9dec-7aec8072a4f2.jpg)

**Comment by ERIFRA2712** [comment]
Hello!

When using DropPlan in a project, it does not load:

![image](https://user-images.githubusercontent.com/40471397/41734827-b71b28bc-754d-11e8-9215-32bd5b14fcf1.png)

Regards.

**Comment by SamanthaEntwistle** [comment]
This is from the console when its not loading

![image](https://user-images.githubusercontent.com/27805840/41773328-9ceb752a-7613-11e8-890c-8a0c0e6ba891.png)

**Comment by SamanthaEntwistle** [comment]
cleared cookies from cache and then got these errors

![image](https://user-images.githubusercontent.com/27805840/41773506-3083fbb8-7614-11e8-9048-2597771a1162.png)

**Comment by SamanthaEntwistle** [comment]
Cleared Cookies and its not saying this anymore - will work on some timeboxes - but not most


This TB works
![image](https://user-images.githubusercontent.com/27805840/41773754-0a8b05b8-7615-11e8-87f4-c3a66479f480.png)


This one doesn't

![image](https://user-images.githubusercontent.com/27805840/41773771-19c77f8e-7615-11e8-85a6-e01a42128903.png)

**Comment by MarkGaze** [comment]
I'm also getting this issue but clearing the cookies didn't solve the issue for me unfortunately.

**Comment by MarkGaze** [comment]
Think I've tracked this down, will send a PR

![image](https://user-images.githubusercontent.com/16718355/41844438-2112b1e6-7868-11e8-97ff-4c0648f1f034.png)

**Comment by yanivsegev** [comment]
Issue fixed, thanks to @MarkGaze 
Can you please confirm it is working now?

**Comment by SamanthaEntwistle** [comment]
Looking good for us!


Samantha Entwistle
Test Manager
[cid:image002.jpg@01CFEFA5.FECB91B0]

Premex Services


Telephone: 01204 478419
Mobile: 07500 781178
Email: samantha.entwistle@premex.com<mailto:samantha.entwistle@premex.com>
Website: www.premexservices.com<http://www.premexservices.com/>
