### ISSUE TITLE
[Feature Request] Filter for User(s)

### ISSUE THREAD

**Issue by drkthng** [yanivsegev/VSTS-DropPlan#41]
Problem:
Want to manage tasks just for me or a certain user.  Currently I see ALL members and have to scroll or Ctrl-F search for member name, which is cumbersome and potentially error-prone

Feature Request:
Have the ability to filter for certain user(s) and only see his/her tasks.

**Comment by yanivsegev** [comment]
Thank you for that suggestion, 
I will try to add it to future releases.
