### ISSUE TITLE
Done flag is incorrectly displayed for Active tasks

### ISSUE THREAD

**Issue by Zeddfred** [yanivsegev/VSTS-DropPlan#44]
![image](https://user-images.githubusercontent.com/41715548/43240502-273ce3c2-90da-11e8-912e-b20b52361429.png)

The tasks for our QA is showing as DONE however it is in active state and linked to Resolved Story. There is remaining hours.. Guessing this is a bug? What is the logic to determine the DONE flag?

**Comment by Zeddfred** [comment]
Have figured out that this occurs when progress hours are added to the completed area
IE 
If Original is 5
Remaining is 1.5
Completed is 3.5
It will show as done.. If Completed is left blank then it will show correctly.. 

We use completed as a progressive number to keep track of work done throughout the sprint by each person - Can you please fix code to only show done if Task status is closed??

**Comment by yanivsegev** [comment]
A task is marked as Done only when its state set to either "done" or "closed".

What is the state of this task?

**Comment by Zeddfred** [comment]
it is active status. No reason to be saying Done
Still broken  - please fix! :)
