### ISSUE TITLE
screen doesn't render when count of work items passed certain number

### ISSUE THREAD

**Issue by myaesubi** [yanivsegev/VSTS-DropPlan#45]
Hello,

Thanks for the extension. It's quite helpful.

However, there is inconsistency that seems to be due to number of work item that Drop plan can show. 

the rendering message shows on screen but it does not load the layout of drop plan anymore. seems there is a work item count limit on rendering the layout.

Thanks,
Mohammad

**Comment by yanivsegev** [comment]
Thank you very much on that.

How many PBIs / Tasks do you have?
There is no limitation set on the drop plan itself, maybe there is a specific issue with one of the tasks.
Can you please open the developer tools and see if there is any error there? can you send me the log of it?
