### ISSUE TITLE
Blocked flag is showing when it isn't blocked

### ISSUE THREAD

**Issue by MADCookie** [yanivsegev/VSTS-DropPlan#46]
We have a task showing the blocked banner when it isn't marked as blocked. Is the logic for the blocked banner just using the blocked field?

*Work Item Details*

![image](https://user-images.githubusercontent.com/359919/43429617-29dc3906-9419-11e8-9d43-03982f400120.png)

*Drop Plan*

![image](https://user-images.githubusercontent.com/359919/43429652-56593920-9419-11e8-82d7-a3b128ba3640.png)

**Comment by yanivsegev** [comment]
Yes,
The blocked flag is turned on only based on field "Blocked" = "Yes".

Can you check again that this field is not set to "Yes"?

**Comment by MADCookie** [comment]
Looks like all my tasks are showing "blocked". Here is my board and the highlighted item. Even the items that are "done" are marked blocked, but since they are done, I can't change the blocked flag. 

![image](https://user-images.githubusercontent.com/359919/43913957-5602be8e-9bbb-11e8-8631-eee44b8cec4f.png)

![image](https://user-images.githubusercontent.com/359919/43913986-6a2b92e6-9bbb-11e8-8c81-fb5978f97915.png)

**Comment by yanivsegev** [comment]
Is this still going on?
Can you provide more data as console logs?
