### ISSUE TITLE
Drop Plan not loading

### ISSUE THREAD

**Issue by Sangeetha-14** [yanivsegev/VSTS-DropPlan#47]
Hi there - 

Drop plan is not loading for some projects or even certain sub projects within a larger project. 

It shows this page and hangs: 
![image](https://user-images.githubusercontent.com/42353696/44046964-15578a16-9efb-11e8-8348-cbb89b4d4451.png)

**Comment by KathirvelMariappan** [comment]
I am also facing exact same issue

**Comment by yanivsegev** [comment]
Hi,

Can you please open the developer tools (F12) and send me the console log?

Yaniv.

**Comment by KathirvelMariappan** [comment]
Hi,

I have this ready for you :)

{"$id":"1","innerException":null,"message":"%error=\"1660002\";%:The
collection does not exist\r\n%error=\"1660002\";%:The collection does
not exist","typeName":"Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.DocumentCollectionDoesNotExistException,
Microsoft.VisualStudio.Services.ExtensionManagement.WebApi","typeKey":"DocumentCollectionDoesNotExistException","errorCode":0,"eventId":3000}


*Thanks & Regards,*
*Kathirvel Mariappan.*
*+91 96770 69009*

**Comment by yanivsegev** [comment]
Thanks,
Can you add the entire log so I can see the context of it? This is the inner exception of the framework.

**Comment by rossj81** [comment]
I am having the same issue on Chrome 68.0.3440.106 x64.

Here is the entire log of my console.

`**ms.vss-web.fabric.LX3qYcrIenpeHQzp.min.js:88** t(t){var i=n.call(this,t)||this;return i._renderElement=function(n,t,u){return r.createElement("div",{className:t},u?u(i.props):n&&r.createElement(f.TooltipHost,{content:n,overflowMode:f.TooltipOverflowMode.Parent,directionalHint:0},n))},i._warnDeprecations property 'primaryText' was used but has been deprecated. Use 'text' instead.`

`**dropPlan.min.js?l=2018-08-17T01:09:58.032Z:1665** Stating. (NaN ms.)``

`**tracker.js:13** VSS init. (812.5 ms.)`

`**tracker.js:13** VSS loaded V 1.4.6 VssSDKRestVersion:3.1 VssSDKVersion:2 user: [redacted]. (1481.7000000039116 ms.)`

`**Content?bundle=vss-bundle-basejs-vI1IxAQ10AVWwEoAF6E9t0idR3ZSaZnasnpanuPQzGJ0=:15** Set-Cookie header is ignored in response from url: https://[redacted].visualstudio.com/_apis/WebPlatformAuth/SessionToken. Cookie length should be less than or equal to 4096 characters.`

`**tracker.js:13** Team data loaded. (3252.3000000510365 ms.)`

`**tracker.js:13** Iteration data loaded. (3591.6999999899417 ms.)`

`**[redacted].extmgmt.visualstudio.com/_apis/ExtensionManagement/InstalledExtensions/yanivsegev/Drop-plan-extension/Data/Scopes/User/Me/Collections/%24settings/Documents/DropPlanTheme:1** GET https://[redacted].extmgmt.visualstudio.com/_apis/ExtensionManagement/InstalledExtensions/yanivsegev/Drop-plan-extension/Data/Scopes/User/Me/Collections/%24settings/Documents/DropPlanTheme 404 ()`

`**dropPlan.min.js?l=2018-08-17T01:09:58.032Z:1898** GET https://yanivsegev.gallerycdn.vsassets.io/extensions/yanivsegev/drop-plan-extension/1.4.6/1534473733234/undefined 404 ()`

Hope this helps.

**Comment by yanivsegev** [comment]
Hi,

I was unable to reproduce it and added more logs/alerts - do you see any alert?

Yaniv.

**Comment by rossj81** [comment]
Hi Yaniv
Yes, I now get a JS alert "TypeError: Cannot read property 'valueOf' of undefined"
Ross

**Comment by yanivsegev** [comment]
Hi,

Thank you for your help! I think i got it now, can you please check if that was fixed?

Yaniv.

**Comment by rossj81** [comment]
Hi Yaniv
It's fixed for me now. Thanks very much.
Ross

**Comment by yanivsegev** [comment]
Great! Happy to help!

I would appreciate if you could rate my extension on the market place.

Yaniv..
