### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by SamanthaEntwistle** [yanivsegev/VSTS-DropPlan#5]
When trying to use this extension on a large team it gives the error below

![image](https://user-images.githubusercontent.com/27805840/27683071-b55fc08c-5cbc-11e7-93ce-33162afa7c19.png)

**Comment by yanivsegev** [comment]
Can you please add chrome console log here?

**Comment by SamanthaEntwistle** [comment]
[DropPlan-1499069834792.zip](https://github.com/yanivsegev/VSTS-DropPlan/files/1118880/DropPlan-1499069834792.zip)
As requested

**Comment by yanivsegev** [comment]
There was an issue with WITs without parents.
Fixed now, can you please verify its working for you?

**Comment by SamanthaEntwistle** [comment]
Fantastic – works great now – Thanks !

**Comment by yanivsegev** [comment]
Thanks!
Feel free to leave a review in the marketplace.

**Comment by ravensorb** [comment]
Have you updated the version in the market place?

**Comment by yanivsegev** [comment]
Not since my last comment.
