### ISSUE TITLE
Rearrange tasks: which order

### ISSUE THREAD

**Issue by cldparisi** [yanivsegev/VSTS-DropPlan#50]
Hi Yaniv,
when you click on "Rearrange tasks" DropPlan rearranges tasks but which orde does it use?
Which field or fields?
Stack Rank? Task id? Priority?

I hope Stack Rank but I try and it don't work 

Thanks

**Comment by cldparisi** [comment]
I found it in your code

but I suggest you  a feature

`    function SortWits(items) {

        return items.sort(function (a, b) {

            if (a.isTaskWit && b.isTaskWit) {

                if (!a.StartDate && !b.StartDate) {
                    var parentIda = a.GetParentId();
                    var parentIdb = b.GetParentId();
                    var pa = null, pb = null;

                    if (parentIda == parentIdb) {
                        pa = a.BacklogPriority || 0;
                        pb = b.BacklogPriority || 0;
                    } else {
                        items.forEach(function (item, index) {
                            if (item.Id == parentIda) pa = item.BacklogPriority || 0;
                            if (item.Id == parentIdb) pb = item.BacklogPriority || 0;
                        });

			// EDIT
			if (pa == pb){
				pa = a.BacklogPriority || 0;
				pb = b.BacklogPriority || 0;
			}
			//END EDIT

                    }

                    if ((pa || 0) != 0 && (pb || 0) != 0) {
                        return pa - pb;
                    }
                } else if (!a.StartDate && b.StartDate) {
                    return 1;
                } else if (a.StartDate && !b.StartDate) {
                    return -1;
                }


            }

            return a.Id - b.Id;
        });
    }`

**Comment by yanivsegev** [comment]
Thanks,
I have accepted your change and deployed it,
Please let me know if that works for you.
