### ISSUE TITLE
Bugs included in the task leveling?

### ISSUE THREAD

**Issue by cjg-cp** [yanivsegev/VSTS-DropPlan#52]
How do you get Bugs to be included in the task leveling process?  It doesn't appear to be using the Effort field.

**Comment by yanivsegev** [comment]
On the backlog board, You can open the setting - working with bugs - set it to manage bugs with tasks.

**Comment by cjg-cp** [comment]
Thank you for your quick response.  Yes,  "Bugs are managed with tasks." in the Work -> General page.

The Effort on the Bugs is not used in the leveling of bugs with the tasks from the PBIs.
