### ISSUE TITLE
Drop plan disappears on Chrome 72.0.3626.121 

### ISSUE THREAD

**Issue by dmognaschi** [yanivsegev/VSTS-DropPlan#55]
The drop plan is initially hidden. 
Hovering over a task it appears an stays visible for about 1sec, then disappears.

![drop-plan-disappearing](https://user-images.githubusercontent.com/22174766/54184845-e42ea480-44a7-11e9-952a-03f485f865a5.gif)

**Comment by zellspell** [comment]
I am on the same version of Chrome (on Windows 7 Pro) and I do not experience this behavior.  Moreover, we are using the Scrum process in TFS (a different guidance than the one you show in your example).
