### ISSUE TITLE
Drop Plan View Sunday - Thursday not Monday to Friday

### ISSUE THREAD

**Issue by Nutty81** [yanivsegev/VSTS-DropPlan#56]
Hello,

We have an issue with users seeing Sunday to Thursday and not Monday to Friday for their sprint.

Users with the same permissions and also using Microsoft Edge 42.17134.1.0 see it Monday to Friday.

Task in Column 1 relate to the  first day of the week in the view, so if a user who sees Sunday to Thursday moves a Sunday task. this moves the task to Tuesday for a user that is still seeing Monday to Friday.

Can you please advise.

![User2](https://user-images.githubusercontent.com/48754907/54679509-5c781400-4aff-11e9-871d-5b5483f62213.jpg)

![User 1](https://user-images.githubusercontent.com/48754907/54679608-a06b1900-4aff-11e9-9b85-2cbcb2e14db6.JPG)

**Comment by khookl** [comment]
Hello,

I have the same problem too. My 7 days sprint header is different from the date from and date to I set for my sprint. Any resolution yet?
