### ISSUE TITLE
Closed tasks

### ISSUE THREAD

**Issue by SamanthaEntwistle** [yanivsegev/VSTS-DropPlan#6]
What should the behaviour be with closed tasks? Don't seem to change colour or disappear from Drop Plan when moved to closed state?

Thanks
Sam

**Comment by yanivsegev** [comment]
What do you mean by closed task? 
if a task is at "done" state then it will be colored with green.
if a task is at "removed" state it will disappear from the drop plan

**Comment by SamanthaEntwistle** [comment]
Hi,

We’re using the Agile Process so the states are

[cid:image001.png@01D30137.C3458AA0]

I think Done is on the Scrum process?

Thanks
Sam

**Comment by yanivsegev** [comment]
Hi

The image was to uploaded, can you please share it again.

**Comment by SamanthaEntwistle** [comment]
![image](https://user-images.githubusercontent.com/27805840/28455673-befb290a-6df7-11e7-9494-f3980b8efe28.png)
![image](https://user-images.githubusercontent.com/27805840/28455696-d01d9f88-6df7-11e7-956d-9133384a605e.png)

Can you see the state of the task is 'Closed' but is showing in red on drop plan.

Thanks
Sam

**Comment by yanivsegev** [comment]
I added "Closed" as another final state as "Done".
Can you check and let me know if that worked?

**Comment by SamanthaEntwistle** [comment]
Thanks for fixing it. That’s looking really good now ☺
Regards

Sam
