### ISSUE TITLE
Receving error "Sprint Drop Plan by Yaniv Segev failed to load"

### ISSUE THREAD

**Issue by bradwist** [yanivsegev/VSTS-DropPlan#62]
We just started receiving this error this morning.

Sprint Drop Plan by Yaniv Segev failed to load.

I don't know if there's a way pull logs to determine what's failing.

Some additional information:
This is on TFS 2018 Update 3 OnPremises.
Version 16.131.28106.2

FYI: Several hours later, this problem has mysteriously resolved itself.  Still not certain of the initial cause

**Comment by hipost** [comment]
Same issue here. It fails randomly and randomly works fine again.
