### ISSUE TITLE
I see users that are not on the team that I have selected

### ISSUE THREAD

**Issue by ramifi** [yanivsegev/VSTS-DropPlan#65]

**Comment by ramifi** [comment]
I see users that are not on the team that I have selected.

**Comment by yanivsegev** [comment]
Hi,

You should see all users that have tasks on the sprint, regardless if they are on your team.

Yaniv.

**Comment by ramifi** [comment]
Can I become a contributor and fix this issue?

**Comment by yanivsegev** [comment]
This is by design, you should track all work done on a sprint by all parties to sync them all together.
If a task is not relevant for the team/sprint then why it is on the team's sprint to begin with?

**Comment by ramifi** [comment]
Each team lead should handle his own team work items.
He should not see the other teams work items

**Comment by ramifi** [comment]
No they are not appear on other tabs.
They should be filtered by the selected team.
