### ISSUE TITLE
Drop plan is not aligned with Sprint dates.

### ISSUE THREAD

**Issue by AMARAVATHIPRASAD** [yanivsegev/VSTS-DropPlan#69]
Team,
This Monday we have started the Sprint. In Drop Plan Friday date is not showing. And also observed that 2 sundays are coming/showing in Dropplan. Please find attachment 1
Further next i have created another sprint now Sprint is starting from Sunday but it suppose to start from Monday. Please find attachment 2.

Please give us a fix for this. Drop plan our teams are very widely using extension. This dates misalignment are confusing us. 

<img width="726" alt="Attachment2" src="https://user-images.githubusercontent.com/73191347/96623795-84f27080-1329-11eb-98c4-ad0d1148dc00.PNG">
<img width="937" alt="Attachment1" src="https://user-images.githubusercontent.com/73191347/96623801-86bc3400-1329-11eb-922e-57fa8ad87acb.PNG">

**Comment by tbauto** [comment]
We got the same concern and our version is 1.6.9 (Latest)
There are even dates that are hidden and some date which are not marked off are showing off.
This issue totally defeats the purpose of this application. I hope a resolution be submitted soon.

**Comment by sgtwilko** [comment]
@AMARAVATHIPRASAD @tbauto 
Is this still an issue?
