### ISSUE TITLE
Installed VSTS-DropPlan, but the menu isn't showing up in sprints

### ISSUE THREAD

**Issue by jd-porter** [yanivsegev/VSTS-DropPlan#8]
Hello,
I've installed Drop Plan into our on-prem farm, but we don't see the Drop plan menu in the sprint planning menu, and none of the console output seems to be emitted either. I've verified the extension's installed in our collection and activated. I ran through the Visual Studio guide for debugging extensions and didn't see any sign it was loaded. Are there any version limitations that we're running into that might not be displayed in the install process? We're running TFS 2015 update 3 (Version 14.102.25423.0) and testing in Chrome 59.0.3071.115

**Comment by yanivsegev** [comment]
There should be a new tab "Drop Plan" next to the sprint board.
Are you using the Scrum process template?
