### ISSUE TITLE
Capacity hours only based on "Development Hours"

### ISSUE THREAD

**Issue by Syssrn** [yanivsegev/VSTS-DropPlan#80]
In my team, we are using multiple "disciplines" on the task level and hour allocation. But the DropPlan only sum the hours set to "Development" Discipline - so even though the total capacity for the person is 20 hours, only 10 hours will be displayed as these are the hours allocated for development.

**Comment by sgtwilko** [comment]
Hi @Syssrn 
DropPlan now adds up all the time for the person.
Can you confirm this is solved for you in the latest version?
