### ISSUE TITLE
Hard to see which tasks/bugs relate to which stories

### ISSUE THREAD

**Issue by dancooktoptal** [yanivsegev/VSTS-DropPlan#81]
Hi, love the tool!
At the moment, its hard to see which tasks relate to which stories. Could there be a tool-tip on hover (or a side-panel on-click?) so that we can see more than just the first few words of the parent story (most of ours, we just see "As a user I wan...." !

**Comment by yanivsegev** [comment]
Good idea,
On 2.0.11 you can click on the story to expand it a bit.
WDYT?
