### ISSUE TITLE
I cant move users tasks on the drop plan

### ISSUE THREAD

**Issue by JamesHarriskocho** [yanivsegev/VSTS-DropPlan#83]
I am currently working on a project with a team of 4. For some reason, I have the ability to move 2 of the teams tasks around to plan out a sprint, but for the other two I cannot. This is strange because the 2 who I cant move tasks, they have the ability to move their own. Does anybody have similar issues?

**Comment by sgtwilko** [comment]
Hi @JamesHarriskocho 
Is this still an issue for you on the latest version?
