### ISSUE TITLE
I Can't open the details

### ISSUE THREAD

**Issue by baooai911** [yanivsegev/VSTS-DropPlan#84]
I'm trying to open the task in detail when I click a item in the grid, It's still in loading forever. This issue came when I change the time and locate follow my country.
Does anybody have similar issues?

**Comment by m4d3laine** [comment]
Hello. I am encountering the same kind of issue. Whenever I open a task from the Drop Plan, it doesn't display the details of the task and just keeps on loading.
This issue started after the boards update of Azure Devops.

**Comment by gparreira** [comment]
Same issue here, I can use Drop Plan as a task viewer and organizer but can't edit the individual tasks. It stays loading forever. Tried using Edge and Chrome with the same result. Any news on that???

**Comment by tomeriksnow** [comment]
Hi any luck go get this to work again?

**Comment by ovpr** [comment]
I have same problem when trying open task details in drop plan. Did someone get this resolved?

**Comment by sgtwilko** [comment]
I believe this will be fixed in the next version once pr #107 is merged.
