### ISSUE TITLE
What does the rearrange tasks button do

### ISSUE THREAD

**Issue by MarkGTI** [yanivsegev/VSTS-DropPlan#88]
Very nervous about clicking it. Will it change the sequence of STORIES/BUGS in my backlog (I hope not)

**Comment by pedrocbt21** [comment]
This button just rearranges the tasks in your drop plan, it doesn't affect the backlog.

**Comment by sgtwilko** [comment]
@yanivsegev   suggest we close this as it's a question, not an issue.
