### ISSUE TITLE
What dates are ACTUALLY being used in the extension?

### ISSUE THREAD

**Issue by ssteiner1** [yanivsegev/VSTS-DropPlan#91]
We thought it was the Start Date and Finish Date.  However, when we drag a task to span multiple days on the Sprint Drop Plan board, those dates aren't updated.  So are there any dates being used by the extension and if so, what are they?  Thanks!

**Comment by sgtwilko** [comment]
Hi @ssteiner1 
You're correct DropPlan does set the `StartDate` and `FinishDate` fields on the Task, but just on the task you won't see anything on parent.
It's irritating that DevOps will cache the details on the history tab, so if you're going in and out to check what's changed you won't see it until you refresh the browser.

**Comment by sgtwilko** [comment]
@yanivsegev  suggest we close this as it's a question, not an issue.
