### ISSUE TITLE
Extension stopped working on new Boards HUB 

### ISSUE THREAD

**Issue by cfmano** [yanivsegev/VSTS-DropPlan#96]
Recently, MS dropped new Boards HUB pages that look similar to old ones, however internal functionality most likely has changed. Using these new Boards, extension stops loading at all. After disabling this new feature via "Preview features settings" popup, extensions starts loading again.

This should be resolved until old pages are replaces permantently.

**Comment by sgtwilko** [comment]
Hi @cfmano  
I'm using the new Boards hub, but not seeing an issue.
Is this still broken for you?
